server:
  port: 8080
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #publisher-confirm-type: correlated
    #publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        default-requeue-rejected: false #拒绝的消息是否被重新放回队列
