server:
  port: 8080
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 20000 #连接超时时间（毫秒）
    password: #密码
    pool:
      minIdle: 1 #最小空闲连接
      maxIdle: 10 #最大空闲连接
      maxWait: 3 #最大阻塞等待时间（使用负值表示没有限制）
      maxActive: 8 #最大连接数（使用负值表示没有限制）
  datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: 12345678

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true